---
sidebar: sidebar 
permalink: scpivs44_create_backup_policies_for_vms_and_datastores.html 
keywords:  
summary: Você deve criar políticas de backup antes de usar o plug-in do SnapCenter para VMware vSphere para fazer backup de VMs e datastores. 
---
= Crie políticas de backup para VMs e armazenamentos de dados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve criar políticas de backup antes de usar o plug-in do SnapCenter para VMware vSphere para fazer backup de VMs e datastores.

.Antes de começar
* Você deve ter lido os pré-requisitos.
* Você deve ter relacionamentos de storage secundário configurados.
+
** Se você estiver replicando cópias Snapshot em um storage secundário de espelhamento ou cofre, os relacionamentos deverão ser configurados e o administrador do SnapCenter deverá ter atribuído as VMs de storage aos volumes de origem e de destino.
** Para transferir cópias Snapshot com êxito para o armazenamento secundário para relacionamentos Version-FlexibleMirror em um datastore NFS ou VMFS, verifique se o tipo de política SnapMirror é espelhamento assíncrono e se a opção "All_source_snapshots" está marcada.
** Quando o número de cópias Snapshot no storage secundário (espelho-cofre) atingir o limite máximo, a atividade para Registrar backup e aplicar retenção na operação de backup falha com o seguinte erro: `This Snapshot copy is currently used as a reference Snapshot copy by one or more SnapMirror relationships. Deleting the Snapshot copy can cause future SnapMirror operations to fail.`
+
Para corrigir esse problema, configure a política de retenção SnapMirror para o storage secundário para evitar alcançar o limite máximo de cópias Snapshot.

+
Para obter informações sobre como os administradores atribuem recursos aos usuários, consulte o https://docs.netapp.com/us-en/snapcenter/concept/concept_types_of_role_based_access_control_in_snapcenter.html["Informações do SnapCenter sobre como usar o controle de acesso baseado em função"^].



* Se você quiser backups consistentes com VM, precisa ter as ferramentas VMware instaladas e em execução. As ferramentas da VMware são necessárias para silenciar as VMs. Os backups consistentes com VM não são suportados para VMs Vevolve.


.Sobre esta tarefa
A maioria dos campos nessas páginas do assistente são auto-explicativos. As informações a seguir descrevem alguns dos campos para os quais você pode precisar de orientação.

.Passos
. No painel Navegador esquerdo do plug-in SCV, clique em *políticas*.
. Na página *políticas*, selecione *criar* para iniciar o assistente.
. Na página *Nova política de backup*, selecione o vCenter Server que usará a política e insira o nome da política e uma descrição.
+
** Modo ligado
+
No modo vinculado, cada vCenter tem um dispositivo virtual separado. Portanto, você pode usar nomes duplicados em vCenters. No entanto, você deve criar a política no mesmo vCenter que o grupo de recursos.

** Carateres não suportados
+
Não use os seguintes carateres especiais em nomes de VM, datastore, cluster, política, backup ou grupo de recursos: % E * / : * ? " > - | ; " , .

+
Um caractere de sublinhado (_) é permitido.



. Especifique as definições de retenção.
+

IMPORTANT: Você deve definir a contagem de retenção para backups de 2 ou superior se quiser habilitar a replicação do SnapVault. Se você definir a contagem de retenção para 1 backup para manter, a operação de retenção pode falhar. Isso ocorre porque a primeira cópia Snapshot é a cópia Snapshot de referência para a relação SnapVault até que a cópia Snapshot mais recente seja replicada para o destino.

+

NOTE: O valor máximo de retenção é de 1018 backups para recursos no ONTAP 9.4 ou posterior e 254 backups para recursos no ONTAP 9.3 ou anterior. Os backups falharão se a retenção for definida para um valor maior do que o que a versão subjacente do ONTAP suporta. Isso também é verdade para armazenamentos de dados de expansão. Se um armazenamento de dados de expansão incluir recursos no ONTAP 9.3 e anterior e no ONTAP 9.4 e posterior, certifique-se de definir o valor de retenção abaixo de 254.

. Especifique as definições de frequência.
+
A política especifica apenas a frequência de backup. O cronograma de proteção específico para backup é definido no grupo de recursos. Portanto, dois ou mais grupos de recursos podem compartilhar a mesma política e frequência de backup, mas têm agendas de backup diferentes.

. Nos campos *replicação*, especifique o tipo de replicação para armazenamento secundário, conforme mostrado na tabela a seguir:
+
|===
| Para este campo... | Faça isso... 


| Atualize o SnapMirror após a cópia de segurança  a| 
Selecione esta opção para criar cópias espelhadas de conjuntos de backup em outro volume que tenha uma relação SnapMirror com o volume de backup primário. Se um volume for configurado com uma relação de cofre-espelho, você deve selecionar somente a opção *Atualizar SnapVault após o backup* se quiser que os backups sejam copiados para os destinos do cofre-espelho.


NOTE: Essa opção é compatível com datastores no FlexGroup volumes no plug-in do SnapCenter para VMware vSphere 4,5 e posterior.



| Atualize o SnapVault após a cópia de segurança  a| 
Selecione esta opção para executar a replicação de backup de disco para disco em outro volume que tenha uma relação de SnapVault com o volume de backup primário.


IMPORTANT: Se um volume estiver configurado com uma relação de cofre-espelho, você deverá selecionar somente essa opção se desejar que os backups sejam copiados para os destinos do cofre-espelho.


NOTE: Essa opção é compatível com datastores no FlexGroup volumes no plug-in do SnapCenter para VMware vSphere 4,5 e posterior.



| Etiqueta do instantâneo  a| 
Insira um rótulo personalizado opcional a ser adicionado às cópias Snapshot do SnapVault e do SnapMirror criadas com esta política. O rótulo Snapshot ajuda a distinguir os snapshots criados com essa política de outros snapshots no sistema de storage secundário.


NOTE: É permitido um máximo de 31 carateres para etiquetas de cópia Snapshot.

|===
. Opcional: Nos campos *Avançado*, selecione os campos necessários. Os detalhes do campo Avançado estão listados na tabela a seguir.
+
|===
| Para este campo... | Faça isso... 


| Consistência da VM  a| 
Marque esta caixa para silenciar as VMs e criar um snapshot do VMware sempre que a tarefa de backup for executada.

Esta opção não é suportada para vVols. Para VMs Vevolve, apenas backups consistentes com falhas são executados.


IMPORTANT: Você precisa ter ferramentas VMware em execução na VM para executar backups consistentes com VMs. Se o VMware Tools não estiver em execução, um backup consistente com falhas será executado.


NOTE: Ao marcar a caixa consistência da VM, as operações de backup podem levar mais tempo e exigir mais espaço de armazenamento. Nesse cenário, as VMs são primeiro silenciadas, depois a VMware executa um snapshot consistente da VM, depois a SnapCenter executa sua operação de backup e, em seguida, as operações da VM são retomadas. A memória convidada da VM não está incluída nos instantâneos de consistência da VM.



| Inclua datastores com discos independentes | Marque esta caixa para incluir no backup todos os datastores com discos independentes que contenham dados temporários. 


| Scripts  a| 
Insira o caminho totalmente qualificado do prescritor ou postscript que você deseja que o plug-in SnapCenter VMware seja executado antes ou depois das operações de backup. Por exemplo, você pode executar um script para atualizar traps SNMP, automatizar alertas e enviar logs. O caminho do script é validado no momento em que o script é executado.


NOTE: Os Prescripts e postscripts devem estar localizados na VM do dispositivo virtual. Para inserir vários scripts, pressione *Enter* após cada caminho de script para listar cada script em uma linha separada. O caráter ";" não é permitido.

|===
. Clique em *Add.*
+
Você pode verificar se a política foi criada e revisar a configuração da política selecionando-a na página políticas.


